spring:
  datasource:
    url: jdbc:postgresql://${POSTGRESQL_HOSTNAME:localhost}:${POSTGRESQL_PORT:5432}/${POSTGRESQL_DB_NAME:kryptokrona_api_dev}
    username: ${POSTGRESQL_DB_USER:postgres}
    password: ${POSTGRESQL_DB_PASSWORD:test1234}
#  jpa:
#    hibernate:
#      ddl-auto: create
  liquibase:

    enabled: false

logging:
  level:
    org:
      kryptokrona:
        api:
          syncer: DEBUG

apiServerUrl: ${SYS_API_SERVER_URL}