spring:
  datasource:
    url: jdbc:postgresql://${POSTGRESQL_HOSTNAME}:${POSTGRESQL_PORT}/${POSTGRESQL_DB_NAME}
    username: ${POSTGRESQL_DB_USER}
    password: ${POSTGRESQL_DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: update

apiServerUrl: ${SYS_API_SERVER_URL}